#!/usr/bin/env bash
# Bash script - prints "Holberton School" 10 times and "Hi" in 9th iteration times
index=1
while [ $index -le 10 ]
do
	echo "Best School"
	if ((index==9)) 
then
	echo "Hi"
fi
index=$((index+1))
done
