#!/usr/bin/env bash
# script displaying " good luck" "Holberton School" "bad luck" 
index=1
while [ $index -le 10 ]
do
	if ((index==4))
	then
	echo "bad luck"
	elif ((index==8))
	then
	echo "good luck"
	else
	echo "Best School"
	fi
	index=$((index+1))
done
