#!/usr/bin/env bash
# "bad luck from China" 4th iteration
# "bad luck from Japan" 9th iteration
# "bad luck from Italy" 17th iteration

index=1
while [ $index -lt 21 ]
do
    echo $index
    case $index in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    index=$(( index+1 ))
done
