#!/usr/bin/env bash
#  Script bash gives you information about the holbertonschool file

file="holbertonschool"

if [ -e "$file" ]
then
    echo "holbertonschool file exists"
    if [ -s "$file" ]
    then
	echo "holbertonschool file is not empty"
	if [ -f "$file" ]
	then
	    echo "holbertonschool is a regular file"
	fi
    else
        echo "holbertonschool file is empty"
	if [ -f "$file" ]
	then
            echo "holbertonschool is a regular file"
	fi
    fi
else
    echo "holbertonschool file does not exist"
fi
