#!/usr/bin/env bash
# Let’s install the ufw firewall and setup a few rules on web-01.
sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
